### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollToBufferPosition' of undefined

### ISSUE THREAD

**Issue by rschaaf** [VoiceCode/atom-voicecode#3]
This happened when I tried to say "spring five three" in Atom while in the FileBrowser tab provided by that package you suggested.  It is only happening in that tab.  I get the same error if I try to use commands like "spackle" or "sprinkle".  

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [voicecode](https://github.com/VoiceCode/atom-voicecode) package, v0.11.0
### Stack Trace

Uncaught TypeError: Cannot read property 'scrollToBufferPosition' of undefined

```
At /Users/*****/.atom/packages/voicecode/lib/voicecode.coffee:73

TypeError: Cannot read property 'scrollToBufferPosition' of undefined
  at Object.Voicecode.goToLine (/Users/*****/.atom/packages/voicecode/lib/voicecode.coffee:73:11)
  at Object.Voicecode.commandRecieved (/Users/*****/.atom/packages/voicecode/lib/voicecode.coffee:52:7)
  at Socket.<anonymous> (/Users/*****/.atom/packages/voicecode/lib/voicecode.coffee:32:12)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```
### Commands

```
     -5:08.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -5:02.7.0 core:move-down (div.settings-view.pane-item)
     -4:45.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:48.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:19.3.0 file-browser:open (button.btn.icon.enablement.icon-playback-play)
     -1:47 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:19.3.0 core:undo (atom-text-editor.editor.file-browser.is-focused)
     -1:02.7.0 tree-view:toggle (atom-text-editor.editor.file-browser.is-focused)
     -0:41.8.0 core:undo (atom-text-editor.editor.file-browser.is-focused)
     -0:24.9.0 core:page-down (atom-text-editor.editor.file-browser.is-focused)
  2x -0:09.2.0 core:undo (atom-text-editor.editor.file-browser.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "auto-reveal-in-sidebar"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
file-browser, v0.4.0
voicecode, v0.11.0

# Dev
No dev packages
```

**Comment by rschaaf** [comment]
btw: those commands – spring etc – don't work.  I just get the error.  

This file-browser package is pretty much exactly what I was looking for. If the spring command would just work, the package would suit my purpose very well.

**Comment by dimatter** [comment]
since file browser is not and editor instance => we can't 'spring' inside of it.
